on:
    workflow_call:
    # workflow_run:
    #     workflows: ["Rialto API Test"]
    #     types:
    #         - completed

jobs:
    slack-notification:
        runs-on: ubuntu-latest

        steps:
            - name: send slack-notification
              env:
                MEMBER_IDS: ${{ vars.MEMBER_IDS }}
                SLACK_APP_WEBHOOK_URL: ${{ vars.SLACK_APP_WEBHOOK_URL }}
              run: |
                # MEMBER_ID=$(echo $MEMBER_IDS | jq -r ".${{ github.actor }}")

                FATAI=$(echo $MEMBER_IDS | jq -r '.["${{ vars.FATAI }}"]')
                echo $FATAI

                PR_TITLE="${{ github.event.pull_request.title }}"

                JOB_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

                NOTIF_TEXT="Some \`test\` checks for the Pull Request _*$PR_TITLE*_ were not successful.\nSee $JOB_URL\nActor involved <@$MEMBER_ID>"
                
                # curl -X POST -H "Content-Type: application/json" -d "{\"text\": \"$NOTIF_TEXT\", \"icon_emoji\": \":sos:\", \"username\": \"Github Action\", \"channel\": \"#github-pull-requests\"}"  $SLACK_APP_WEBHOOK_URL


                    